### ISSUE TITLE
cannot run randoop successfully

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#10]
according to the [tutorial of randoop](https://github.com/CastleLab/COMP5111-assignment-Student-Version/blob/assignment1/randoop.md) as below:

![](https://user-images.githubusercontent.com/25791058/110237431-0c5a1c80-7f77-11eb-81c3-13809e498a58.png)

I use the following comand(win10 platform),%RANDOOP_PATH% and %RANDOOP_JAR% have been set as computer environmental variables. 
*  %RANDOOP_PATH% is the randoop directory(`C:\GreenSoftware\Java_Packages\randoop-4.2.5`)
*  %RANDOOP_JAR% is `randoop-all-4.2.5.jar`

![](https://user-images.githubusercontent.com/25791058/110237593-cc476980-7f77-11eb-9f64-4b8f73ccbf56.png)

~~~
java -ea -classpath %RANDOOP_PATH%\%RANDOOP_JAR%;.\target\classes\ randoop.main.Main gentests --testclass=comp5111.assignment.cut.ToolBox --time-limit=60 --junit-package-name=comp5111.assignment.cut --junit-output-dir=./src/test/randoop0
~~~

but I come cross the following error

![](https://user-images.githubusercontent.com/25791058/110237564-a91cba00-7f77-11eb-81c0-44444d0d770c.png)

**Comment by qqblack** [comment]
I got it!  The command is for command prompt window, not powershell!

**Comment by aaromine** [comment]
Classpath may need to be wrapped by quotes in Powershell. 

Thanks for pointing out the mistake in the tutorial. 
Good to know that the current command works in cmd.

**Comment by qqblack** [comment]
There are two differences between powershell comand and cmd comand

|name|cmd|powershell|
|-|-|-|
|environment variable|`%env_name%`|`$env:env_name`|
|classpath parameter|-classpath value|-classpath "value"|

**Comment by aaromine** [comment]
Thanks for the information. I am not quite familiar with windows.
