### ISSUE TITLE
Class not found comp5111.assignment.cut.RegressionTest

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#11]
I have generated the test cases by randoop, but when I run them in Eclipse, I came across the issue as below:

![](https://user-images.githubusercontent.com/25791058/110242077-40413c00-7f8f-11eb-8616-70c5d1a9c36b.png)

**Comment by aaromine** [comment]
It's hard to say what is wrong with this screenshot. Are you sure the test suite is compiled and the compiled `.class` is in classpath?

**Comment by qqblack** [comment]
When I only added one randoop test suite to the build path before runing, the issue disappeared.

select one randoop test suite folder and then click right button, `Build Path`-`Remove from Build Path` (`Add to Build Path` )

![图片](https://user-images.githubusercontent.com/25791058/113379146-4d452580-93ab-11eb-9252-cd596fa74e89.png)
