### ISSUE TITLE
Commas in statements, .csv file

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#14]
As some statements contain commas (e. g. "$stack5 = virtualinvoke $stack4.<java.lang.String: java.lang.String substring(int,int)>(0, l1)"), I wanted to ask if have to manipulate these commas (remove, replace) before inserting them in the .csv file. Is the format "statement" as above accepted?

**Comment by aaromine** [comment]
You can leave the commas as they are. Alternatively ,you can generate `tsv` files, which are also acceptable.
