### ISSUE TITLE
goto statement to soot method

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#15]
When instrumenting ToolBox with internalTransform and adding InvokeExpr incExpr in this method , there are some goto statements generated that point to my soot method (e.g., goto [?= staticinvoke <comp5111.assignment.cut.Counter: void addInvocationNoStmtReached(int)>). 

In case there is no InvokeExpr added  in internalTransform, these statements are defined as goto [?= (branch)].

The number of total statements remains the same.

I wanted to ask how to treat these statements: Shall we drop them, or keep them in the set of statements. It affects around 30 statements.

**Comment by aaromine** [comment]
I don't quite understand your cases here. Can you give a concrete example?

**Comment by mpriorust** [comment]
<img width="1368" alt="InvokeExpressionAdded" src="https://user-images.githubusercontent.com/78396786/113093147-e8aa8f00-9221-11eb-82a3-3c73db32e17b.png">
Above you see methodSignature, statement, index of the Jimple code. Here an InvokeExpr is added in internalTransform

<img width="1378" alt="NoInvokeExpressionAdded" src="https://user-images.githubusercontent.com/78396786/113093156-eea07000-9221-11eb-9c37-e42ddaf3b6f3.png">
Above you see methodSignature, statement, index of the Jimple code. No InvokeExpr is added in internalTransform

I indexed all statements to track them. Both statements have index 908.

**Comment by aaromine** [comment]
You can just keep them in the output. 

Be sure the semantics are not changed after your instrumentation.
