### ISSUE TITLE
[Specification] What's the format of spectrum reports?

### ISSUE THREAD

**Issue by maybeLee** [CastleLab/COMP5111-assignment-Student-Version#17]
Since CUT ToolBox.java has multiple inner classes, I want to know which format is suitable for spectrum reports.

Format 1: list and sort all statements in ToolBox.java
Example:
[spectrum report for test suite 1]
method1, stmt1, score1, ranking1
method2, stmt2, score2, ranking2,
...

Format 2: list and sort all statement in subclass level
Example:
[spectrum report for test suite 1]
inner class: RegExTools
method1, stmt1, score1, ranking1
method2, stmt2, score2, ranking2
inner class: CharTools
method1, stmt1, score1, ranking1
method2, stmt2, score2, ranking2

The difference between format 2 and format 1 is that: format 2 will calculate the suspicious score and rank the suspicious statement only considering all statements **in the same inner class**; in contrast, format 1 will consider **all statements together in ToolBox.java** to calculate the score and rank the statement.

I am wondering are both formats ok?

**Comment by aaromine** [comment]
It is better to use format 1, since the ranking is among all statements in ToolBox.java, not in each inner class.

**Comment by maybeLee** [comment]
Thanks for your reply.
