### ISSUE TITLE
initializationError after all provided tests run successfully

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#18]
I receive the following errors after fixing the injected bugs, and all provided tests run successfully:

initializationError(comp5111.assignment.cut.ToolBox_FaultRevealing0_ESTest_scaffolding)
initializationError(comp5111.assignment.cut.ToolBox_FaultRevealing1_ESTest_scaffolding)
initializationError(comp5111.assignment.cut.ToolBox_FaultRevealing2_ESTest_scaffolding)

JUnit counts them as test failures and also links them to Jimple statements. As these failures are not related to your testcases, I wanted to ask if we shall count, drop or fix them (if possible).

**Comment by Troublor** [comment]
I suspect that the error is related to [FAQ-Q1](https://github.com/CastleLab/COMP5111-assignment-Student-Version/blob/assignment2/Assignment2_FAQ.md#q1-i-cannot-run-test-cases-generated-by-evosuite-in-eclipseeclemma-fails-to-report-coverage-for-the-test-cases-generated-by-evosuite). 
Please see if it is applicable.

**Comment by mpriorust** [comment]
I followed the instructions in FAQ-Q1, but it seems to not solve the issue.

<img width="768" alt="Screenshot 2021-04-03 at 16 55 45" src="https://user-images.githubusercontent.com/78396786/113473679-983f6580-949d-11eb-88d4-ad3c0b7d271d.png">

The problem appears only when running:
comp5111.assignment.cut.ToolBox_FaultRevealing0_ESTest_scaffolding
comp5111.assignment.cut.ToolBox_FaultRevealing1_ESTest_scaffolding
comp5111.assignment.cut.ToolBox_FaultRevealing2_ESTest_scaffolding
from the fault revealing evosuite test suites.

My question is how to treat these failures: Shall I include them and link them to statements as test failures, or drop them (e.g. by not running ToolBox_FaultRevealing0_ESTest_scaffolding.java, ToolBox_FaultRevealing1_ESTest_scaffolding.java, ToolBox_FaultRevealing2_ESTest_scaffolding.java?

**Comment by aaromine** [comment]
I see. You can ignore the errors in the *_scaffolding.
