### ISSUE TITLE
Format: Location in source code, fixing patch

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#19]
Does location in source code mean the line number?

Regarding the format of the fixing patch:
Initial:
"Java code of initial line"
Fixed:
"Java code of fixed line"

Is the above format as fixing patch accepted?

**Comment by pca006132** [comment]
Also, is it OK to put git diff as the patch?

**Comment by aaromine** [comment]
> Does location in source code mean the line number?

Yes. Line number in the source code.

> Regarding the format of the fixing patch:
Initial:
"Java code of initial line"
Fixed:
"Java code of fixed line"

The format is acceptable.

**Comment by aaromine** [comment]
@pca006132 Git diff is also acceptable. 

Note that you are not supposed to actually fix it in the ToolBox.java. You should keep ToolBox.java unchanged in Assignment 2.
