### ISSUE TITLE
Could you put out the answer of assignment1 for reference?

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#20]
Could you put out the answer of assignment1 for reference? So, we can understand the contents better, and it's also helpful for assignment2.

Thank you!

**Comment by aaromine** [comment]
There is no standard answer for the assignments and assignments are highly related to each other. We are not going to release our implementation for sake of fairness.

**Comment by qqblack** [comment]
I think it's unreasonable. If a student have trouble on assignment1, he will have trouble on every following assignment. Then he will fail this course.

**Comment by xiaoxstz** [comment]
I don' t think it reasonable either.

It just like,"I will not give the answer of the assignments or midterm exam, even after they have passed over. Because, some of the questions are similar with the final exam" .It's ridiculous!
