### ISSUE TITLE
How to understand the Assignment1 solution,as there are 24 java files

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#22]
How to understand the Assignment1 solution,as there are 24 java files？

It's a little bit crazy.

![](https://user-images.githubusercontent.com/25791058/113509209-ebd9ae00-9586-11eb-8fd0-b081e697c568.png)

I guess some of them are generated automaticly by some framework？Thank you!

**Comment by aaromine** [comment]
A lot of them only contains tens of lines of code........

- `instrument` package contains classes that is related to instrumentation. 
- `runtime` are classes that will be called by the instrumented CUT during runtime. 
- `coverage` contains classes related specific kinds of coverage type, `*TestRequirement` will be used in runtime and `*Instrumenter` defines how instrumentation should be carried on for the type of coverage.

**Comment by qqblack** [comment]
Personaly, the key files are
* **runtime\CoverageCounter.java
* **runtime\TestRequirementCollection.java
