### ISSUE TITLE
Jimple statements associated with the same line executed by different tests

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#24]
If different Jimple statements, that are associated with the same line number, are executed by a different set of tests, does this imply an error or is it possible?

**Comment by aaromine** [comment]
I think it implies nothing. 
Suppose we have an one-line if statement: 
```java
if (obj == null) throw new InvalidArgument();
```
This line may generate several Jimple statements. 

No matter whether there is a bug or not, it is completely possible that some tests visits one branch, while others visits the other branch, i.e., they execute different Jimple statements in this line.

**Comment by mpriorust** [comment]
Great! Thanks for the example
