### ISSUE TITLE
Grading Task 3/ Rank of faulty statements

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#26]
Is the before and after refinement ranking of a faulty statement calculated as average of the 6 test-suites? Otherwise, no points can be obtained for faulty statements that rank already top before refinement in a specific test-suite.

**Comment by aaromine** [comment]
Yes it's average of all test suites.

**Comment by mpriorust** [comment]
Sorry that I have to ask more precise - hope my questions finds you well: So is the ranking the average of all faulty statements combined, or is the average ranking of each distinct faulty statement meant?

**Comment by aaromine** [comment]
Average ranking (amount all test suites) of each distinct faulty statement.
