### ISSUE TITLE
Unclear about ranking suspicious statement

### ISSUE THREAD

**Issue by maybeLee** [CastleLab/COMP5111-assignment-Student-Version#27]
> Ranking of Suspicious Statements
The ranking of a statement with suspicious score $a$ should be computed as $\frac{N+M+1}{2}$, where N is the number of statements whose suspicious scores are higher than $a$ and M is the number of statements whose suspicious scores are higher than or equal to $a$. For example, if a sequence of suspicious scores is (0.9, 0.8, 0.8, 0.8, 0.8, 0.7) their rankings are (1, 3, 3, 3, 3, 6), respectively.

It is unclear whether we should include the target statement when generating ranking. Following the setting, to get the ranking of suspicious score: 0.8, N=1, and M=5 (if we include the target statement), in this case, the ranking of this statement should be $\frac{1+5+1}{2}=3.5$ instead of 3. However, if we exclude the target statement, even though the ranking of 0.8 is $\frac{1+4+1}{2}=3$, the ranking of 0.9 is $\frac{0+0+1}{2}=0.5$ instead of 1.

Do we also do rounding? If so, how is the rounding conduct (floor, ceiling. etc)?

**Comment by aaromine** [comment]
It is integer division operation. We use implicit floor. 

The ranking of 0.9 should be floor((0+1+1)/2) = 1

**Comment by maybeLee** [comment]
Thanks for your explanation.
