### ISSUE TITLE
All the coverage results of assignment1-TA_implementation are 0

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#28]
Why are all the coverage results of assignment1-TA_implementation 0? The pictures below are reports of `assignment1-TA_implementation`. 
Thank You!

![图片](https://user-images.githubusercontent.com/25791058/113640180-73b9d800-96ad-11eb-97be-4010617ccef9.png)

![图片](https://user-images.githubusercontent.com/25791058/113640241-8a602f00-96ad-11eb-8a48-bb156b50cf1a.png)

![图片](https://user-images.githubusercontent.com/25791058/113640278-a19f1c80-96ad-11eb-9f78-1661bfdba2fd.png)

**Comment by Troublor** [comment]
Since you are using Windows, could you provide the arguments when calling main class?

**Comment by qqblack** [comment]
statement coverage:

`0 comp5111.assignment.cut.ToolBox comp5111.assignment.cut.ToolBox$ArrayTools comp5111.assignment.cut.ToolBox$CharSequenceTools comp5111.assignment.cut.ToolBox$CharTools comp5111.assignment.cut.ToolBox$LocaleTools comp5111.assignment.cut.ToolBox$RegExTools comp5111.assignment.cut.ToolBox$StringTools`

branch coverage:

`0 comp5111.assignment.cut.ToolBox comp5111.assignment.cut.ToolBox$ArrayTools comp5111.assignment.cut.ToolBox$CharSequenceTools comp5111.assignment.cut.ToolBox$CharTools comp5111.assignment.cut.ToolBox$LocaleTools comp5111.assignment.cut.ToolBox$RegExTools comp5111.assignment.cut.ToolBox$StringTools`

line coverage:

`2 comp5111.assignment.cut.ToolBox comp5111.assignment.cut.ToolBox$ArrayTools comp5111.assignment.cut.ToolBox$CharSequenceTools comp5111.assignment.cut.ToolBox$CharTools comp5111.assignment.cut.ToolBox$LocaleTools comp5111.assignment.cut.ToolBox$RegExTools comp5111.assignment.cut.ToolBox$StringTools`

![图片](https://user-images.githubusercontent.com/25791058/113648455-36f6dc80-96bf-11eb-8f15-87e37b35c52f.png)

**Comment by aaromine** [comment]
The second argument should be the test suite class. This is a little different from the template of assignment 1. 

Try:
```
0 
comp5111.assignment.cut.Regression_0_Test
comp5111.assignment.cut.ToolBox comp5111.assignment.cut.ToolBox$ArrayTools comp5111.assignment.cut.ToolBox$CharSequenceTools comp5111.assignment.cut.ToolBox$CharTools comp5111.assignment.cut.ToolBox$LocaleTools comp5111.assignment.cut.ToolBox$RegExTools comp5111.assignment.cut.ToolBox$StringTools
```

**Comment by qqblack** [comment]
When I do it as you mentioned, I come across this error:`Exception in thread "main" java.lang.ClassNotFoundException: comp5111.assignment.cut.Regression_0_Test`

![图片](https://user-images.githubusercontent.com/25791058/113650465-d4074480-96c2-11eb-87be-608a6f67fa51.png)

Then I add `"./target/test-classes"` into set_soot_classpath,but the error still appears.(`Regression_0_Test.class` can be found in the directory `.\target\test-classes\comp5111\assignment\cut`)

![图片](https://user-images.githubusercontent.com/25791058/113650717-46782480-96c3-11eb-9344-72c4a704608b.png)

**Comment by aaromine** [comment]
The error is not that soot cannot find the class, it is java cannot find the class. 
Maybe you should add it to java classpath.

**Comment by qqblack** [comment]
Thank you!

But after doing that, I come across some new issues.

# issue1
when running line coverage,and branch coverange, there are a lot of `Warning: cannot retrieve line number from method`(statement coverage sames okay)

![图片](https://user-images.githubusercontent.com/25791058/113653797-192e7500-96c9-11eb-9408-4b85541dd0d3.png)


# issue2
 the report of line coverage

![图片](https://user-images.githubusercontent.com/25791058/113653984-70344a00-96c9-11eb-86a7-1e76a24cf29f.png)

 the report of branch coverage

![图片](https://user-images.githubusercontent.com/25791058/113654093-affb3180-96c9-11eb-923a-6dda47ef971f.png)

**Comment by aaromine** [comment]
Well, every time you need to re-compile the CUT. 
In the given scripts, we use `mvn clean compile` to clean the previously compiled class files and re-compile. 

This is because the class file of CUT is modified after the instrumentation. If you do not re-compile the CUT, you are instrumenting on the already-instrumented class files.

**Comment by qqblack** [comment]
It's really helpful.The issues are solved!

Thank you very much!
