### ISSUE TITLE
how to add target\test-classes to classpath?

### ISSUE THREAD

**Issue by qqblack** [CastleLab/COMP5111-assignment-Student-Version#29]
To solve the issue `Exception in thread "main" java.lang.ClassNotFoundException: comp5111.assignment.cut.ToolBox_FaultRevealing0_ESTest`

I am trying to add the `target\test-classes` to classpath. But, I am not sure how to add it. The piture below shows the issue I come across

![图片](https://user-images.githubusercontent.com/25791058/113678009-c23c9600-96f0-11eb-9ce6-63d7eb4c4a6f.png)

**Comment by aaromine** [comment]
Mark `src/test/randoop0` as Source Folder in Eclipse and recompile the project. The test suite will be compiled along with the CUT. 
<img width="576" alt="Screenshot 2021-04-06 at 17 38 18" src="https://user-images.githubusercontent.com/79785755/113691316-e1422480-96fe-11eb-9535-d89a1583beda.png">

**Comment by qqblack** [comment]
I had done it before. But it doesn't help.

Eventually, I solve the issue by changing their output directory from `.target\test-calsses` to `.target\calsses`

Before the change  
![](https://images.gitee.com/uploads/images/2021/0406/165017_d26c7c4c_1107360.png)

After the change  
![](https://images.gitee.com/uploads/images/2021/0406/165120_7b4b6834_1107360.png)

**Comment by qqblack** [comment]
But I found this solution is temporary, sad

**Comment by qqblack** [comment]
But, after I changed the test suites' output directory to `.\target\classes` , everytime `mvn clean compile` will clean their `.class` file

**Comment by pca006132** [comment]
Maybe you can try to run the code with a shell script instead of from the IDE. It is much easier to see what is going on and get it working with shell scripts rather than dealing with the IDE GUI.

**Comment by qqblack** [comment]
OK, thank you
