### ISSUE TITLE
Methods are not invoked when running JUnit tests

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#6]
Dear Aaron,

I used the code from the soot-example to transform ToolBox.java into Jimple IR. To get a better understanding, I wanted to insert counter instructions before static and instance method returns as in the workshop example. After transforming the code to Jimple IR and inserting the invocation counters, I programatically ran my JUnit tests for ToolBox.

While it works fine for the soot example project (Subject.java):
<img width="492" alt="Screenshot 2021-02-28 at 22 46 38" src="https://user-images.githubusercontent.com/78396786/109422722-c0a7f000-7a17-11eb-9ae6-669d9f4b5281.png">

It says that there were no method invocations for the COMP5111-assignment-Student-Version project (ToolBox.java):
<img width="434" alt="Screenshot 2021-02-28 at 23 10 31" src="https://user-images.githubusercontent.com/78396786/109423409-33b26600-7a1a-11eb-84e3-aa34b724fde2.png">
 
I presume this is wrong because there are static and instance methods in ToolBox. Do you know why the methods are not invoked/ counted when running the JUnit tests? Might it be related to the soot-classpath settings? 

Kind regards,

Max Prior

**Comment by aaromine** [comment]
One possible reason is that you failed to instrument the CUT, probably because you didn't specify the inner class to soot, so that soot didn't not instrument any inner classes. 

Could you first make sure the instrumentation is successful?
