### ISSUE TITLE
Instruction count

### ISSUE THREAD

**Issue by pca006132** [CastleLab/COMP5111-assignment-Student-Version#7]
I can only count 1117 instructions in the `ToolBox.java` (including subclasses) when I iterate over all Jimple instructions in `internalTransform` (with `JIdentityStmt` counted). This seems significantly lower than the count reported by EclEmma which is 2029, is this normal?

However, the coverage percentage seems similar (52.7% in EclEmma, 54.2% by my code when `JIdentityStmt` are excluded).

**Comment by aaromine** [comment]
This is normal. Eclemma uses different IR compared with soot. The total number of statements/instructions is indeed different. But the overall coverage should be close. 

Your result only have 2% deviation from the coverage of Eclemma. It looks fine, although it cannot be guaranteed that your implemented is correct.
