### ISSUE TITLE
Class loader priority

### ISSUE THREAD

**Issue by pca006132** [CastleLab/COMP5111-assignment-Student-Version#8]
I am using the `URLClassLoader` to load the instrumented `ToolBox.class` and the test class files for JUnit runner. However, it seems that the class loader would load the original `ToolBox.class` instead of the one in the `sootOutput` directory. Is there a way to modify the priority? (sorry I am not really familiar with java...)

Currently, I can only run the program by changing the `ToolBox.java` to another filename to avoid being compiled and loaded...

This is the related code segment:
```java
URL[] urls = new URL[]{
    new File("./sootOutput/").toURI().toURL(),
    new File("./target/test-classes/").toURI().toURL(),
};
ClassLoader cl = new URLClassLoader(urls);
Class<?> cls = cl.loadClass("comp5111.assignment.cut.RegressionTest");
```

**Comment by aaromine** [comment]
Soot instrumentation does not require `ToolBox` in the class path of java. `ToolBox` is only needed to be in the soot class path. So one simple way is to not put the original `ToolBox.class` in Java's classpath and put the instrumented `ToolBox.class` in the Java's classpath instead.
