### ISSUE TITLE
How to present the coverage of each statement/branch/line in output file?

### ISSUE THREAD

**Issue by CometMoon** [CastleLab/COMP5111-assignment-Student-Version#9]
In the program output section it says the program should contains 1) The coverage of each statement/branch/line (statement/branch/line, yes or no). and 2) The coverage for each class (percentage), including inner classes.

I am confused on how to show 1) the coverage of each statement/branch/line. Does it mean that for statement coverage I need to export files containing all Jimple code from ToolBox and add "yes" after the executed line?

For example:
if i0 < 10 goto label0;, yes
    $r1 = <java.lang.System: java.io.PrintStream out>;, no
    $r2 = new java.lang.StringBuilder;, no
    specialinvoke $r2.<java.lang.StringBuilder: void <init>(java.lang.String)>("I made ");, no
    $i1 = <TestInvoke: int calls>;, no

**Comment by aaromine** [comment]
There is no format requirement for the output. Your example is fine for statement coverage.

**Comment by CometMoon** [comment]
Okay. Thank you.
